name: Flutter CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter pub get
    - run: flutter build apk --release
      #Publish to release
    - name: Release apk
      uses: ncipollo/release-action@v1.5.0
      with:
        artifacts: "build/app/outputs/apk/release/release-app.apk"
        token: ${{ secrets.GITHUB_RElEASE_TOKEN }}