name: Flutter CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter pub get
    - run: flutter build apk --release
    - run: flutter build apk --release --build-number=${GITHUB_RUN_NUMBER}
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.GITHUB_RElEASE_TOKEN }}
        commit: master
        tag: v1.0.${{ github.run_number }}